name: Check
on:
  pull_request:
    types: [ labeled ]
  issue_comment:
    types: [ created ]
jobs:
  check:
    if: ${{ github.event.issue.pull_request }} &&
        ${{ github.event_name == 'issue_comment' && github.event.comment.body == 'recheck' }} ||
        ${{ github.event.label.name == 'check' }}
    runs-on: ubuntu-22.04

    steps:
      - run: echo Running check pipeline.
